### ISSUE TITLE
Configuración disqus

### ISSUE THREAD

**Issue by aurora-mareviv** [eliocamp/codigo-r#1]
Buenas!  

Ante todo, enhorabuena por tu blog, resulta un entretenimiento leer tus posts!   
Lo he tomado como base para rehacer un poco el mío y evitar el **master** branch en GitHub Pages, también he adaptado tu **config.toml**, pero me ocurre lo siguiente:  mi Disqus sigue sin cargar adecuadamente.   
Dado que en tu blog se ve a la perfección, intuyo que el problema debe ir en la propia cuenta de disqus. Yo tengo un *shortname* para la página en cuestión, y la URL que puse en Disqus es la misma que en el apartado `baseURL = ` de **config.toml**, pero continúa sin cargar.  

Hay alguna cosa específica que se me esté escapando? muchas gracias, un saludo cordial

**Comment by eliocamp** [comment]
La verdad que ni idea. Yo puse el shortname en el `config.toml` y listo. En disqus, creo que ni siquiera le dije el url, jeje.
