### ISSUE TITLE
Translation of the article “The new R pipe”

### ISSUE THREAD

**Issue by LuWinter** [eliocamp/codigo-r#3]
I have read your article **The new R pipe** on R-bloggers. I think it is a good article which introduces the new feature of R 4.1.0.
While Chinese R community lacks deep exploration of such a topic, I translated it into Chinese on Zhihu,  a knowledge-share website in China. Here is the [link](https://zhuanlan.zhihu.com/p/451590575). 
_Since there's no explicit license attached, I assume this is copyrighted material. If you think it is not appropriate, I will withdraw it_

**Comment by eliocamp** [comment]
Wow, this is awesome! Thanks for the heads up.
